### ISSUE TITLE
update.sh gone?

### ISSUE THREAD

**Issue by egradman** [satoruhiga/ofxZmq#7]
I see `libs/update.sh` is gone in the latest commit.  I'm having compilation problems on Raspberry Pi 2, and I assume it's because I haven't run `./configure` (previously, `update.sh` took care of that.)

Is there a new way to download the zmq version and configure it for my platform, or should `update.sh` be restored?

**Comment by satoruhiga** [comment]
Hi,

I removed a update.sh because that was not usable for cross platform.

I have wanted to use same source for OSX and Windows. finally I hand-patched platform.hpp, I think you can add some options then you will use on RPi.
https://github.com/satoruhiga/ofxZmq/blob/master/libs/zmq/src/platform.hpp#L39-L48

or just call `sudo aptitude install libzmq3` ?

**Comment by egradman** [comment]
on raspbian-jessie, installing libzmq3-dev and removing the libs directory worked great.  I added `-lzmq` to my LDFLAGS.  Thanks!

**Comment by satoruhiga** [comment]
nice!
